### PR TITLE
Create fortnite

### PR DESCRIPTION
**Pull request by lbak25**

### CODE REVIEW

**Comment by rifting** [comment]
Someone merge this PR. This adds a lot to the software, makes it tremendously better, and fixes our longest standing issue.

**Comment by Notplayingallday383** [comment]
fr please merge pr

**Comment by velzie** [comment]
wow, this fixes our longest standing issue. please merge

**Comment by VillainsRule** [comment]
this fixes world hunger. merge asap.

**Comment by m-qur** [comment]
bro this is the goated pr i hope tn does it it would make uv so much better

**Comment by tuta-amb** [comment]
this is really such an important PR, I'm amazed that @lbak25 was able to do this!!!!!!!!

**Comment by ProgrammerIn-wonderland** [comment]
Thanks for the PR, This adds a lot to the software, makes it tremendously better, and fixes our longest standing issue.

**Comment by zkayns** [comment]
Thanks for the PR, This adds a lot to the software, makes it tremendously better, and fixes our longest standing issue.

**Comment by MadjikDotPng** [comment]
Thanks for the PR, this does indeed add a lot to the software.

**Comment by kxtzownsu** [comment]
This adds a lot to the software, makes it tremendously better, and fixes our longest standing issue.

**Comment by proudparrot2** [comment]
This finally adds support for roblox, thank you!!!!

**Comment by bypassiwastaken** [comment]
Finally, the issues that have been plaguing this repo for so long are fixed! All in one commit too, impressive work!

**Pull request merged**
