### PR TITLE
Remove Holy Unblocker from README.md

### PR DESCRIPTION
**Pull request by jamescc10**
Holy Unblocker's maintainer Susshi/David/Divide as recently started a scam. If people join the Holy Unblocker discord server they can get their money stolen.

### CODE REVIEW

**Comment by proudparrot2** [comment]
He realized his mistake and has repealed the program. Holy Unblocker is perfectly safe.
Even if it was still active, there’s no reason to remove it as the link goes to their GitHub, not Discord

**Comment by rifting** [comment]
being investigated

**Comment by velzie** [comment]
> He realized his mistake and has repealed the program. Holy Unblocker is perfectly safe. Even if it was still active, there’s no reason to remove it as the link goes to their GitHub, not Discord

this is not true. hu development is now happening under a new organization unrelated to divide and the current "Holy Unblocker" is not safe

**Comment by proudparrot2** [comment]
Got it, thanks for the clarification

**Comment by kxtzownsu** [comment]
Please refer to this HedgeDoc
[https://pad.nixnet.services/s/aa7a3QowC](https://pad.nixnet.services/s/aa7a3QowC)

**Pull request closed without merging**
