### PR TITLE
Fix SrcSet & CSS issues

### PR DESCRIPTION
**Pull request by quotingg**
this fixes issues with both srcset images and styles not being rewritten
also added **HTMLSourceElement** to srcset since it wasn't added for some reason?

### CODE REVIEW

**Comment by Percslol** [comment]
@quotingg this did not fix the srcset rewriting issues, the other stuff is good though

**Comment by quotingg** [comment]
hey, @Percslol i made some changes the srcset rewriting issues should be fixed now

**Comment by Percslol** [comment]
@quotingg the srcset regex still seems broken

image
this was the site i was using to test: https://russmaxdesign.github.io/srcset/

**Comment by quotingg** [comment]
@Percslol okay now finally it should work

**Comment by Percslol** [comment]
seems to work now, thanks

**Pull request merged**
