### PR TITLE
Delete fortnite

### PR DESCRIPTION
**Pull request by VillainsRule**

### CODE REVIEW

**Comment by NovaAppsInc** [comment]
I don't think we can do this, it would destroy the stability for UV.

**Comment by MadjikDotPng** [comment]
No thanks for the PR, This adds nothing to the software, makes it tremendously worse, and brings back our longest standing issue.

**Comment by ghost** [comment]
Fortnite is borderline necessary for UV as it is right now.

**Comment by MrEnder0** [comment]
I think this good to merge upstream @ProgrammerIn-wonderland could you review & merge this PR.

**Comment by rifting** [comment]
This makes the build fail, and it's outside of the project scope. Do you even use the software?

**Comment by MadjikDotPng** [comment]
[img](https://share.creavite.co/tswUSv7TVgeoQlys.gif)

**Comment by Percslol** [comment]
Removing fortnite would damage UV in its current state, we need to make some more changes before this gets merged upstream.

**Comment by bomberfish** [comment]
I strongly oppose removing fortnite, it would break all future builds and cause massive instability.

**Comment by VillainsRule** [comment]
My bad. I did not realize Fortnite was this critical to the software and will soon opt to improve this feature.

**Comment by zkayns** [comment]
npm fart

**Comment by proudparrot2** [comment]
Thank you for not merging this pull request. It would cause breaking changes across all dependents.

**Comment by MrEnder0** [comment]
this has to be merged this is needed

**Comment by MrEnder0** [comment]
this is a mistake I tell you

**Review by incognitotgt — COMMENTED** [review]
This is dogshit now UV is broken

**Pull request closed without merging**
