### PR TITLE
Delete the "fortnite" file 🤨

### PR DESCRIPTION
**Pull request by i-am-henri**

### CODE REVIEW

**Comment by Percslol** [comment]
deleting fortnite would make uv unstable and unusable for most

fortnite is a crucial part of uv and should NOT be deleted

closing

**Comment by kxtzownsu** [comment]
i test most pr's and they mostly work, this literally does not get past `npm i`.

this fucks up everything so badly that it made my cmos battery die

**Comment by proudparrot2** [comment]
the fortnite file is a vital part of ultraviolet's codebase. i don't think you realize what consequences would occur to many ultraviolet users if this had been merged.

**Comment by ghost** [comment]
the fortnite file ensures stability when using ultraviolet. ultraviolet requires this file as one of its dependencies. the file came from a node_module known as "fortnite" and can be installed using "npm i -g fortnite", but it's actually so important for ultraviolet that they moved it to the root directory just in case npm doesn't download it right.

deleting the file would cause catastrophic errors.

**Pull request closed without merging**
